TwitterAPI/Models/Twitter/UserOauthTokensModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Newtonsoft.Json;

namespace TwitterAPI.Models.Twitter
{
    public class UserOauthTokensModel
    {
        //Temporary ApiClient credentials:
        public string RequestAuthToken { get; set; }
        public string RequestAuthVerifier { get; set; }

        //Token credentials:
        [JsonProperty("oauth_token")]
        public string UserAccessToken { get; set; }

        [JsonProperty("oauth_token_secret")]
        public string UserAccessTokenSecret { get; set; }

        [JsonProperty("user_id")]
        public string TwetterUserId { get; set; }

        //Additional properties
        public string Message { get; set; }
        public bool IsSuccessful { get; set; }
        public string UserName { get; set; }
        public string UserScreenName { get; set; }
        public string UserImageUrl { get; set; }
    }
}

TwitterAPI/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace TwitterAPI.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

TwitterAPI/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace TwitterAPI.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

TwitterAPI/Pages/TwitterSettings.cshtml.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Options;
using Newtonsoft.Json;
using RestSharp;
using Tweetinvi;
using Tweetinvi.Auth;
using Tweetinvi.Exceptions;
using Tweetinvi.Parameters;
using TwitterAPI.Models.Twitter;
using TwitterAPI.Services.TwitterAPI;

namespace TwitterAPI.Pages
{
    public class TwitterSettings : PageModel
    {
        private static readonly IAuthenticationRequestStore _tweeterAuthRequestStore = new LocalAuthenticationRequestStore();
        public TwitterApiOptions Options { get; }

        private readonly IPostTweetsAPI _twitterApi;

        public TwitterSettings(IOptions<TwitterApiOptions> optionsAccessor, IPostTweetsAPI twitterApi)
        {
            Options = optionsAccessor.Value;
            _twitterApi = twitterApi;
        }
        [TempData]
        public string StatusMessage { get; set; }
        private string OAuthToken { get; set; }

        private string OAuthVerifier { get; set; }
        private string AuthorizationKey { get; set; }
        private string AuthorizationSecret { get; set; }
        private string QueryString { get; set; }
        public UserOauthTokensModel TwitterUser { get; set; }

        public async Task<IActionResult> OnGet()
        {
            OAuthToken = HttpContext.Request.Query["oauth_token"].ToString();
            OAuthVerifier = HttpContext.Request.Query["oauth_verifier"].ToString();
            //QueryString = Request.QueryString.Value;

            this.StatusMessage = string.Empty;
            await LoadAsync();
            return Page();
        }

        private async Task LoadAsync()
        {
            bool isUserAuthorize = false;
            bool isAuthenticatedUser = false;
            if (!string.IsNullOrWhiteSpace(OAuthToken) && !string.IsNullOrWhiteSpace(OAuthVerifier))
            {
                TwitterUser = await _twitterApi.GetUserAuthorize(this.OAuthToken, this.OAuthVerifier);
                isUserAuthorize = TwitterUser.IsSuccessful ? true : false;
                isAuthenticatedUser = TwitterUser.IsSuccessful ? true : false;
            }
            if (!isUserAuthorize)
            {
                UserOauthTokensModel storedTwitterUser = _twitterApi.ReadTokensFile();
                isAuthenticatedUser = await _twitterApi.CheckUserAuthentication(storedTwitterUser);
                if (isAuthenticatedUser)
                {
                    TwitterUser = storedTwitterUser;
                }
            }
            this.StatusMessage = isAuthenticatedUser ? "Your Twitter account is authenticated." : "Please, authenticate your Twitter account!";
        }

        //Step 1: POST oauth/access_token and Step 2: GET oauth/authorize
        //documentation-https://developer.twitter.com/en/docs/authentication/oauth-1-0a/obtaining-user-access-tokens
        public async Task<ActionResult> OnPostTwitterSigninAsync()
        {
            try
            {
                TwitterClient appClient = new TwitterClient(Options.TwitterApiKey, Options.TwitterApiSecretKey);
                string authenticationRequestId = Guid.NewGuid().ToString();
                string redirectPath = Request.Scheme + "://" + Request.Host.Value + "/Identity/Account/Manage/TwitterSettings";
                string redirectURL = _tweeterAuthRequestStore.AppendAuthenticationRequestIdToCallbackUrl(redirectPath, authenticationRequestId);
                Tweetinvi.Models.IAuthenticationRequest authenticationRequestToken = await appClient.Auth.RequestAuthenticationUrlAsync(redirectURL);
                return new RedirectResult(_twitterApi.GetTwitterApiAuthentication(authenticationRequestToken, authenticationRequestId));
            }
            catch (TwitterException)
            {
                this.StatusMessage = "Unauthorized - Twitter API  Authentication credentials were missing or incorrect";
            }
            catch (Exception)
            {
                // Other system exceptions like SocketException if you do not have internet
                this.StatusMessage = "System Exception";
            }


            return Page();
        }

        public async Task<ActionResult> OnPostTweetUpdateAsync()
        {
            UserOauthTokensModel respObj = _twitterApi.ReadTokensFile();

            //UserOauthTokensModel respObj = await _twitterApi.GetUserAuthorize(Request.Form["OAuthToken"], Request.Form["OAuthVerifier"]);
            if (respObj.IsSuccessful)
            {
                //string json = JsonConvert.SerializeObject(respObj);

                //_twitterApi.WriteTokensFile(respObj);
                var tweet = await _twitterApi.PostTweetAsync(respObj);
                this.StatusMessage = "Success";
            }
            else
            {
                this.StatusMessage = respObj.Message;
            }
            return Page();
        }
    }
}

TwitterAPI/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

TwitterAPI/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TwitterAPI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">TwitterAPI</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/TwitterSettings">Twitter Settings</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - TwitterAPI 
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

TwitterAPI/Pages/Shared/_StatusMessage.cshtml
@model string

@if (!String.IsNullOrEmpty(Model))
{
    var statusMessageClass = Model.StartsWith("Error") ? "danger" : "success";
    <div class="alert alert-@statusMessageClass alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @Model
    </div>
}

TwitterAPI/Pages/TwitterSettings.cshtml
@page
@model TwitterAPI.Pages.TwitterSettings
@{
    ViewData["Title"] = "Twitter settings";
    string authToken = Request.Query["oauth_token"].ToString();
    string authVerifier = Request.Query["oauth_verifier"].ToString();
    var backgroundImage = Model.TwitterUser != null ? Model.TwitterUser.UserImageUrl : "";
    var userName = Model.TwitterUser != null ? Model.TwitterUser.UserName : "";
    var userScreenName = Model.TwitterUser != null ? string.Concat("@", Model.TwitterUser.UserScreenName) : "";
}
<h4 class="text-left mt-4">@ViewData["Title"]</h4>
<script src="~/js/AccountTwitter.js" onload="activeMenuMyA();"></script>
<div class="row">
    <div class="col-md-12">

        @if (!string.IsNullOrWhiteSpace(userName))
        {
            <div class="mb-3">
                <img src="@backgroundImage" class="img_profileBig" />
            </div>
            <div>
                <label><strong>@userName</strong></label>
            </div>
            <div class="mb-5">
                <label class="edit_Photo">@userScreenName</label>
            </div>
        }
        <form id="profile-form" method="post" enctype="multipart/form-data">
            <div class="row">
                <div class="col-md-12 text-left mt-4">
                    <div class="row">

                        <div class="col-md-12 text-left">
                            <div class="form-groupdaje s">
                                <button id="bstatusYT" type="submit" asp-page-handler="twittersignin" class="colorprof font_18"> Twitter Account Authentication</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
        <form id="profile-form" method="post" enctype="multipart/form-data">
            <div class="row">
                <div class="col-md-12 text-left mt-4">
                    <div class="row">
                        <div class="col-md-12 text-left">
                            <input type="hidden" name="OAuthToken" value=@authToken />
                            <input type="hidden" name="OAuthVerifier" value=@authVerifier />
                            <div class="form-groupdaje s">
                                <button id="bstatusYT" type="submit" asp-page-handler="TweetUpdate" class="colorprof font_18"> Post Tweet</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
        <br><br><partial name="_StatusMessage" model="Model.StatusMessage" />
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}